/**
* HolderComposite ABE 
* @see <a href="URL#https://www.tmforum.org/Browsable_HTML_SID_R16.5/content/_3E3F0EC000E93E2C3D3900F5-content.html">HolderComposite ABE</a> 
* @since SID_R16.5
*/

package org.tmforum.resource_domain.resource_abe.physicalresource_abe.equipment_holder_abe.holdercomposite_business_entity ;

/**
* A Chassis is a type of SecureHolder that encloses other ManagedPhysica 
* lEntities and provides a definable functionality in its own right, suc 
* h as a desktop or a network device (e.g., a router or a switch). 

Inheritance tree: |- 
 <a title="SID Models::Resource Domain::Resource ABE::PhysicalResource ABE::Equipment Holder ABE::HolderComposite ABE::SecureHolder" href="_3E3F0EC000E93CDD708302D6-content.html">SID Models::Resource Domain::Resource ABE::PhysicalResource ABE::Equipment Holder ABE::HolderComposite ABE::SecureHolder</a> |- 
 <a title="SID Models::Resource Domain::Resource ABE::PhysicalResource ABE::Equipment Holder ABE::HolderComposite ABE::HolderComposite" href="_3E3F0EC000E93DDEEB160255-content.html">SID Models::Resource Domain::Resource ABE::PhysicalResource ABE::Equipment Holder ABE::HolderComposite ABE::HolderComposite</a> |- 
 SID Models::Resource Domain::Resource ABE::PhysicalResource ABE::Equipment Holder ABE::EquipmentHolder |- 
 SID Models::Resource Domain::Resource ABE::PhysicalResource ABE::Hardware ABE::PhysicalContainer |- 
 SID Models::Resource Domain::Resource ABE::PhysicalResource ABE::Hardware ABE::ManagedHardware |- 
 SID Models::Resource Domain::Resource ABE::PhysicalResource ABE::Hardware ABE::Hardware |- 
 SID Models::Resource Domain::Resource ABE::PhysicalResource ABE::PhysicalResource |- 
 SID Models::Resource Domain::Resource ABE::Resource |- 
 SID Models::Common Business Entities Domain::Root Business Entities ABE::Entity |- 
 SID Models::Common Business Entities Domain::Root Business Entities ABE::RootEntity @since SID_R16.5
*/ 

public  class Chassis extends SecureHolder,HolderComposite,EquipmentHolder,PhysicalContainer,ManagedHardware,Hardware,PhysicalResource,Resource,Entity,RootEntity {



/**  
* Field heatGeneration
* This is an integer that defines the amount of heat generated by the Ch 

* assis in BTU/hour. This is an optional attribute. 

*/
protected Integer heatGeneration ;




/**  
* Field installationOrder
* This is a free-form string that defines the order of installation of c 

* omponents into the Chassis. This is an optional attribute. 

*/
protected String installationOrder ;




/**  
* Field powerCordNumber
* This is an integer that defines the number of power cords which must b 

* e connected to the Chassis in order for all of its contained ManagedEn 

* tities to operate correctly. This is an optional attribute. 

*/
protected Integer powerCordNumber ;




/**  
* Field numberOfChassisSlots
* This defines the number of Slots that are in the Chassis. This does NO 

* T account for any SlotAdapters used - these are described by the CardI 

* nSlot association. This is an optional attribute. 

*/
protected Integer numberOfChassisSlots ;




/**  
* Field chassisType
* This is an enumerated integer that defines the type of Chassis that th 

* is object is. Values include:</br></br> 0: Unknown</br> 1: Desktop</br 

* > 2: Low Profile Desktop</br> 3: Pizza Box</br> 4: Mini Tower</br> 5:  

* Tower</br> 6: Portable</br> 7: LapTop</br> 8: Notebook</br> 9: Sub-Not 

* ebook</br> 10: Hand Held</br> 11: Docking Station</br> 12: Main System 

*  Chassis</br> 13: Expansion Chassis</br> 14: Bus Expansion Chassis</br 

* > 15: Peripheral Chassis</br> 16: Storage Chassis</br> 17: Rack Mount  

* Chassis</br></br>This is an optional attribute.</br> 

*/
protected Integer chassisType ;




/**  
* Field chassis
*/
protected List<Chassis> chassis ;




/**  
* Field chassis1
*/
protected Chassis chassis1 ;




/**  
* Field rack
*/
protected Rack rack ;




/**  
* Field physicalPort
*/
protected List<PhysicalPort> physicalPort ;


}