/**
* Alarm Severity Assignment Profile ABE 
* @see <a href="URL#https://www.tmforum.org/Browsable_HTML_SID_R16.5/content/_.uVV.r.oE.mWE.eCN.m.p.x.w.x3LZL.g-content.html">Alarm Severity Assignment Profile ABE</a> 
* @since SID_R16.5
*/

package org.tmforum.resource_domain.resource_trouble_abe.alarm_severity_assignment_profile_business_entity ;

/**
* This object class models the (flexible) severity assignment to specifi 
* ed probable causes. So the ASAP object includes a table, with each row 
*  specifying the probable cause (plus optionally the probableCauseQuali 
* fier and / or the nativeProbableCause) and the assigned severity for " 
* service affecting", "non service affecting" and "service independent o 
* r unknown" alarms.Probable cause, probableCauseQualifier and nativePro 
* bableCause are the coordinates of the ASAP entries, so there must not  
* be two ASAP entries with the same coordinates. It is the responsibilit 
* y of the EMS to enforce this.Alarms against entities that are not mode 
* led by the interface are reported using the "AID" objectType. For thes 
* e "AID" alarms the ASAP mechanism is not applicable.Typically the ASAP 
*  function is implemented in the OS or NE where the alarm is originated 
* . I. e. the severity will usually be assigned directly by the NE, so i 
* t is up to the EMS to download the defined ASAP to the NE. Other alarm 
* s, e.g. on arcs like SNCs, may be generated by the target OS. An alarm 
*  becomes reportable by NE/target OS:- when for PTP, CTP, FTP: AlarmRep 
* orting changes from "off" to "on" - when for SNC, TopologicalLink, Equ 
* ipment, EquipmentHolder, GTP: alarmReportingIndicator changes from fal 
* se to true.Alarms are always reportable for all other objects as they  
* do not have any alarm reporting attribute.When an alarm becomes report 
* able the ASAPs are applied (accessed via the asapPointer). The severit 
* y of the alarm is adopted from the ASAP entry that matches for all of  
* the following:- same probableCause - same probableCauseQualifier (an e 
* mpty string is a match)- same nativeProbableCause (an empty string is  
* a match).For example, if the reportable alarm has LOS probableCause an 
* d an ASAP entry is found with LOS probableCause and both probableCause 
* Qualifier and nativeProbableCause are empty strings, then the search i 
* s successful.If there is a matching ASAP, then the severities are adop 
* ted on the following basis:- the alarm is service affecting: the sever 
* ity specified in the serviceAffecting field is assigned- the alarm is  
* service non affecting: the severity specified in the serviceNonAffecti 
* ng field is assigned- the alarm is service independent or NE/target OS 
*  is not equipped to determine if the alarm affects service or not:  th 
* e severity specified in the serviceIndependentOrUnknown field is assig 
* ned.If the assigned severity specified in the ASAP is:- "FREE_CHOICE"  
* then the NE/target OS are free to determine the severity. If there is  
* no local mechanism on     the ME/EMS to determine severity then the se 
* verity "INDETERMINATE" should be assigned. - "NOTALARMED" then the EMS 
*  should not emit an alarm over the EML-NML interface.If there is no AS 
* AP that matches, then the NE/target OS is free to determine the severi 
* ty. If there is no local mechanism on the NE/target OS to determine se 
* verity then the severity "INDETERMINATE" should be assigned.Once a sev 
* erity has been assigned, the alarm notification is emitted (other than 
*  for "NOTALARMED").Note: Any operation of alarm retrieval will not inc 
* lude "NOTALARMED" alarms. 
 @since SID_R16.5
*/ 

public  class AlarmSeverityAssignmentProfile  {



/**  
* Field isFixed
* This attribute defines if the Alarm Severity Assignment Profile (ASAP) 

*  is fixed or not.</br>If true, then this ASAP instance is fixed, i.e.  

* is an ASAP which is defined at NE or target OS level and can be neithe 

* r modified nor deleted through the interface, but only assigned/de-ass 

* igned. If false, otherwise. 

*/
protected Boolean isFixed ;




/**  
* Field alarmSeverityAssignmentList
* This attribute identifies a list of Alarm Severity Assignments (ASA).  

* Each record of this sequence specifies the probable cause (plus option 

* ally the probableCauseQualifier and / or the nativeProbableCause) and  

* the severities to be assigned. 

*/
protected AlarmSeverityAssignment alarmSeverityAssignmentList ;


}